service: tesseract-ocr-layer

provider:
  name: aws

layers:
  tesseract:
    path: layer
    compatibleRuntimes:
      - python3.8
      - nodejs12.x
      - ruby2.7
      - provided

resources:
  Outputs:
    TesseractOcrLayerArn:
      Description: The ARN for the Tesseract OCR lambda layer.
      Value:
        Ref: TesseractLambdaLayer
      Export:
        Name: TesseractOcrLayerArn
